name: Collect daily market volumes

# 1️⃣ give the workflow write access so the default token can push commits
permissions:
  contents: write

on:
  schedule:
    - cron: '0 2 * * *'      # 02:00 UTC ≈ 22:00 ET
  workflow_dispatch:

jobs:
  update-volumes:
    runs-on: ubuntu-latest

    steps:
      # Checkout with the default GITHUB_TOKEN (no explicit token needed)
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run volume-collector
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: python agent.py

      - name: Commit & push updated CSV
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily_volumes.csv
          git commit -m "data: update volumes $(date -u +'%Y-%m-%d')" || echo "Nothing to commit"
          git push
